### PR TITLE
Replacing configure/config/esgf_shards.xml.template with configure/co…

### PR DESCRIPTION
**Pull request by LucaCinquini**
…nfig/esgf_shards.xml (issue 67).

### CODE REVIEW

**Comment by mkjpryor-stfc** [comment]
@LucaCinquini: Did you see this problem in Docker Compose, or only in Kubernetes?

**Comment by LucaCinquini** [comment]
Just in kubernetes - I think the Docker network will correctly resolve esgf-solr-slave, as it will localhost
(from inside the same container).

**Comment by mkjpryor-stfc** [comment]
@LucaCinquini: I also saw this issue in Kubernetes. The solution is to ensure that "hairpin mode" is configured with your CNI (networking) plugin.

Instructions on how to do this for Minikube are in the `esgf-helm` README.

**Comment by LucaCinquini** [comment]
One additional comment: this doesn't seem to be a problem when using Kubernetes on Google Cloud: the following URL:
http://esgf-solr-slave:8983/solr/datasets/select
is reachable from the index-node container WITHOUT having to place the Docker network in 'hairpin' mode

**Comment by LucaCinquini** [comment]
Sorry, I should have checked access from the solr-slave pod, but that works too:

solr@esgf-solr-slave-59cdcbbccd-knk22:/opt/solr$ curl 'http://esgf-solr-slave:8983/solr/datasets/select'
<?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">0</int><int name="QTime">0</int><lst name="params"><str name="tie">0.01</str><str name="facet.limit">-1</str><str name="df">text</str><str name="q.alt">*:*</str><str name="echoParams">all</str
><str name="qf">text</str><str name="fl">*,score</str><str name="facet.method">enum</str><str name="facet.mincount">1</str><str name="rows">10</str><str name="facet">true</str><str name="facet.sort">lex</str></lst></lst><result name="resp
onse" numFound="0" start="0" maxScore="0.0"></result><lst name="facet_counts"><lst name="facet_queries"/><lst name="facet_fields"/><lst name="facet_dates"/><lst name="facet_ranges"/><lst name="facet_intervals"/><lst name="facet_heatmaps"/
></lst>
</response>

**Comment by LucaCinquini** [comment]
But I don't see any harm in using 'localhost' instead ?

**Comment by mkjpryor-stfc** [comment]
@LucaCinquini: GKE probably already has the appropriate network settings.

The reason I prefer to be explicit, i.e. `esgf-solr-slave` rather than `localhost`, is because the place where this file actually lives, and makes a difference, is `esgf-index`. The use of `localhost` could be confusing for a new person coming to the project, whereas `$ESGF_SOLR_SLAVE` (or whatever it is) is explicit and makes it obvious that we don't mean `esgf-index`.

So I would prefer to stick with `esgf-solr-slave`.

**Comment by mkjpryor-stfc** [comment]
@LucaCinquini 

P.S. You're not testing the right thing there.

http://esgf-solr-slave:8983/solr/datasets/select is always accessible from `esgf-index-node`. What causes the problem is that http://esgf-solr-slave:8983/solr/datasets/select is *not* accessible from `esgf-solr-slave` unless it is in hairpin mode.

**Comment by LucaCinquini** [comment]
Hi Matt,
actually as I mentioned in the comment, when using GKE, the URL  'http://esgf-solr-slave:8983/solr/datasets/select' IS reachable from the esgf-solr-slave pod without setting the Docker network in hairpin mode.
In any case, I typically don't like doing non-standard networking configuration because it might generate problems elsewhere, but since this might turn out to be a problem only when running minikube, let's stick with the current setup. I'm ok with closing this pull request.
Thanks.

**Pull request closed without merging**
