### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by gardoll**
Add the jenkins pipeline script that run esgf-test-suite.

### CODE REVIEW

**Comment by mkjpryor-stfc** [comment]
@gardoll: Am I correct in thinking that this `Jenkinsfile` only tests existing containers? It doesn't yet replace the build and push for Travis CI?

**Comment by gardoll** [comment]
@mkjpryor-stfc: yes you are right. Jenkinsfile trigger only esgf-test-suite on devel and master images of esgf-docker. We will implement the replacement of Travis in the near future.  Can I force the merge as Travis failed to build devel ?

**Comment by mkjpryor-stfc** [comment]
@gardoll: I'd prefer we didn't, as this is a genuine failed build. It looks like a conflict between the version of cryptography used by the SLCS and the openssl version in the container.

The easy fix is to use an earlier container version, but I'd rather not do that. The proper solution is to update the esgf-slcs requirements.txt... :-(

**Comment by gardoll** [comment]
@mkjpryor-stfc: I don't know what to do with the esgf-slcs requirements.txt . Can someone help me ?

**Comment by mkjpryor-stfc** [comment]
@gardoll:  The problem is clearly nothing to do with this PR, so I'm just going to merge it. I'll look at the SLCS problems today, as I think it may need significant updating.

**Comment by mkjpryor-stfc** [comment]
@gardoll: P. S. You didn't really follow the contribution process properly with this PR - I can't see an issue for your change,  and your branch isn't really a feature branch.

I'll let it slide this time...! :-P

**Comment by gardoll** [comment]
@mkjpryor-stfc: so sorry !!! Next time don't let it slide, and kick a 22-metre drop-out ;)

**Pull request merged**
